# Thanks Geo! :-)
[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-args=-z stack-size=33554432",     # 32 MiB
  "-C", "link-args=--initial-memory=134217728", # 128 MiB
  "-C", "link-args=--max-memory=536870912",     # 512 MiB
  "-C", "overflow-checks=false",
  # Browser pthread support was removed from the web frontend, so keep the
  # wasm target features single-threaded here as well.
  "-C", "target-feature=+bulk-memory,+multivalue,+mutable-globals,+sign-ext,+simd128,+tail-call",
  # disabled for iOS Safari support (relaxed-simd not supported, tail-call requires a new version of Safari)
   "-C", "target-feature=+relaxed-simd",
]